// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orders.API.Data;

#nullable disable

namespace Orders.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725171551_SeedStock")]
    partial class SeedStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orders.API.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Orders.API.Entities.Stock", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disponible")
                        .HasColumnType("int");

                    b.HasKey("Sku");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            Sku = "SKU001",
                            Disponible = 10
                        },
                        new
                        {
                            Sku = "SKU002",
                            Disponible = 5
                        },
                        new
                        {
                            Sku = "SKU003",
                            Disponible = 20
                        },
                        new
                        {
                            Sku = "SKU004",
                            Disponible = 40
                        },
                        new
                        {
                            Sku = "SKU005",
                            Disponible = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
